baseURL: "linux.jaybhogayata.me"
languageCode: en-us
title: Linux-Notes
theme: PaperMod

params:
  homeInfoParams:
    Title: "This site is a collection of notes on Linux"

  cover:
    linkfullImages: true

  showBreadCrumbs: true
  showReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON 
